services:
  - type: web
    name: shopping-cart
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_MODE
        value: online
      - key: PORT
        value: 8080
